FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip libgl1 libglib2.0-0 libgomp1 curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-api.txt requirements-worker.txt .

RUN python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel

RUN python3 -m pip install --no-cache-dir \
    torch==2.5.1 \
    --index-url https://download.pytorch.org/whl/cu121

RUN python3 -m pip install --no-cache-dir \
    -r requirements-worker.txt

COPY . .

CMD ["celery", "-A", "worker.tasks", "worker", "--loglevel=info", "--concurrency=1"]
